import { Code, CreditCard, Home, Mail, Palette, Server, Settings, Shield, User } from 'lucide-react'

import type { DashboardExtension } from '../../types'

export const userCenterExtension: DashboardExtension = {
  id: 'builtin.user-center',
  meta: {
    title: '用户中心',
    description: '核心控制台能力，包括账户、管理与观测功能。',
    version: '1.0.0',
    author: 'XControl',
    keywords: ['dashboard', 'accounts', 'management'],
  },
  routes: [
    {
      path: '/panel',
      label: 'Dashboard',
      description: '专属于你的信息总览',
      icon: Home,
      loader: () => import('./routes/home'),
      match: 'startsWith',
      guard: { requireLogin: true },
      redirect: { unauthenticated: '/login' },
      sidebar: { section: '用户中心', order: 0 },
    },
    {
      path: '/panel/account',
      label: 'Accounts',
      description: '目录与多因素设置',
      icon: User,
      loader: () => import('./routes/account'),
      guard: { requireLogin: true },
      redirect: { unauthenticated: '/login' },
      sidebar: { section: '权限设置', order: 0 },
    },

    {
      path: '/panel/mail',
      label: 'Mail',
      description: '租户邮件与 AI 助理',
      icon: Mail,
      loader: () => import('./routes/mail'),
      guard: { requireLogin: true },
      redirect: { unauthenticated: '/login' },
      sidebar: { section: '功能特性', order: 0 },
    },
    {
      path: '/panel/appearance',
      label: 'Appearance',
      description: '个性化主题设置',
      icon: Palette,
      loader: () => import('./routes/theme'),
      guard: { requireLogin: true },
      redirect: { unauthenticated: '/login' },
      sidebar: { section: '个性化设置', order: 0 },
    },
    {
      path: '/panel/agent',
      label: 'Agents',
      description: '管理运行时节点',
      icon: Server,
      loader: () => import('./routes/agent'),
      guard: { requireLogin: true },
      redirect: { unauthenticated: '/login' },
      sidebar: { section: '功能特性', order: 1 },
      featureFlag: {
        id: 'user-center.agent',
        title: 'Agent 管理',
        description: '启用代理节点管理页面。',
        envVar: 'NEXT_PUBLIC_FEATURE_AGENT_MODULE',
        defaultEnabled: false,
      },
    },
    {
      path: '/panel/api',
      label: 'APIs',
      description: '洞察后端服务',
      icon: Code,
      loader: () => import('./routes/api'),
      guard: { requireLogin: true },
      redirect: { unauthenticated: '/login' },
      sidebar: { section: '功能特性', order: 2 },
      featureFlag: {
        id: 'user-center.api',
        title: 'API 监控',
        description: '启用 API 状态与特性开关页面。',
        envVar: 'NEXT_PUBLIC_FEATURE_API_MODULE',
        defaultEnabled: false,
      },
    },
    {
      path: '/panel/subscription',
      label: 'Subscription',
      description: '订阅方案与计费规则',
      icon: CreditCard,
      loader: () => import('./routes/subscription'),
      guard: { requireLogin: true },
      redirect: { unauthenticated: '/login' },
      sidebar: { section: '功能特性', order: 3 },
      featureFlag: {
        id: 'user-center.subscription',
        title: '订阅与计费',
        description: '启用订阅与计费配置页面。',
        envVar: 'NEXT_PUBLIC_FEATURE_SUBSCRIPTION_MODULE',
        defaultEnabled: true,
      },
    },
    {
      path: '/panel/ldp',
      label: 'LDP',
      description: '低时延身份平面',
      icon: Shield,
      loader: () => import('./routes/ldp'),
      guard: { requireLogin: true },
      redirect: { unauthenticated: '/login' },
      sidebar: { section: '权限设置', order: 1 },
      featureFlag: {
        id: 'user-center.ldp',
        title: 'LDP 管理',
        description: '启用低时延身份平面管理模块。',
        envVar: 'NEXT_PUBLIC_FEATURE_LDP_MODULE',
        defaultEnabled: false,
      },
    },
    {
      path: '/panel/management',
      label: 'Management',
      description: '集中化的权限矩阵与用户编排',
      icon: Settings,
      loader: () => import('./routes/management'),
      guard: { requireLogin: true, roles: ['admin', 'operator'] },
      match: 'startsWith',
      redirect: { unauthenticated: '/login', forbidden: '/panel' },
      sidebar: { section: '管理页面', order: 0 },
    },
  ],
}
